### ISSUE TITLE
ERROR net.hollowcube.polar.PolarLoader - Failed to find biome: minecraft:jungle

### ISSUE THREAD

**Issue by FazziCLAY** [hollow-cube/polar#20]
`ERROR net.hollowcube.polar.PolarLoader - Failed to find biome: minecraft:jungle`

**Comment by mworzala** [comment]
Minestom only registers plains by default, you will need to add the rest yourself (load from a registry). I did add https://github.com/hollow-cube/minestom-ce/issues/36 for loading them in ce, but in the mean time you can get the biome infos by loading `/biome.json` from the classpath (it comes from `minestom-ce-data`.
