### ISSUE TITLE
Decorated pot sherds bug

### ISSUE THREAD

**Issue by UserUNP** [hollow-cube/polar#21]
An undecorated decorated pot block turns into a decorated decorated pot with the sword sherd decoration in all sides when saved and loaded using the polar world format

**Comment by UserUNP** [comment]
Actually it might just be changing to a random sherd that's shown on all sides

**Comment by UserUNP** [comment]
This might be a bug related to the mc client actually because just now I logged into a local server and loaded the world
And all the decorated pots were using a very broken texture on all sides and looks like it's been blit to the base decorated pot texture

**Comment by UserUNP** [comment]
(I am using the fabulously optimized mod pack)

**Comment by UserUNP** [comment]
![image](https://github.com/hollow-cube/polar/assets/39243708/49124d57-1c4a-467d-8b78-a80898b0b8de)

**Comment by UserUNP** [comment]
![image](https://github.com/hollow-cube/polar/assets/39243708/f9d68090-5760-43af-9928-19957b6a770a)
never mind its a polar format bug

**Comment by mworzala** [comment]
I'll try to take a look this weekend, though I dont immediately have a guess what would cause it. Polar does very little special with block entities (it just writes and re-reads the nbt on blocks)

**Comment by UserUNP** [comment]
The world is also uploaded as a blob to a PostgreSQL database

**Comment by mworzala** [comment]
Sorry I just re-noticed this issue. I believe this is a lack of block entity data on the pot and client prediction when you actually see them, not a Polar issue.

**Comment by UserUNP** [comment]
ah ok
