### ISSUE TITLE
Getting ByteArray from Instance

### ISSUE THREAD

**Issue by Nopock** [hollow-cube/polar#23]
Hello,

How can u get a byte array from the instance? 

Thanks,

Nopox

**Comment by mworzala** [comment]
A `PolarLoader` can be constructed using the `PolarWorld` constructor, and then saving the world will fill the given world, which can then be written using a `PolarWriter`, eg:

```java
var world = new PolarWorld();
instance.setChunkLoader(new PolarLoader(world));
instance.saveChunksToStorage().join();
var bytes = PolarWriter.write(world);
```
