### ISSUE TITLE
Add support for latest minestom

### ISSUE THREAD

**Issue by mani1232** [hollow-cube/polar#48]

**Comment by mworzala** [comment]
I have no issues with the latest of both, you will have to be more specific about the incompatibility.

**Comment by mani1232** [comment]
![image](https://github.com/user-attachments/assets/00d86e6b-777d-4dc8-abad-c7ebf8084c40)
net.minestom:minestom-snapshots:7320437640

**Comment by mani1232** [comment]
- net.minestom:minestom-snapshots [7d43da919d -> 7320437640]
     https://github.com/minestom/minestom
     
```toml
updateDeps = { id = "com.github.ben-manes.versions", version.ref = "updateVersions" }
```

**Comment by mani1232** [comment]
Wrong version, but why?

**Comment by mani1232** [comment]
#51  with feature
